### ISSUE TITLE
CLI asks for username with token

### ISSUE THREAD

**Issue by lubien** [mathdroid/crop-github-images-cli#5]
```sh
λ ./node_modules/.bin/crop-github-images  dance.gif -t REALTOKEN
Successfully cropped dance.0.gif.
Successfully cropped dance.1.gif.
Successfully cropped dance.2.gif.
Successfully cropped dance.3.gif.
Successfully cropped dance.4.gif.
Successfully cropped dance.5.gif.
Prepared the gist for dance.0.gif in https://gist.github.com/b99cd5eab55244e9c2293cb0d84869fd
Prepared the gist for dance.1.gif in https://gist.github.com/64f3784bdf7852d5d81acc87087c4040
Prepared the gist for dance.5.gif in https://gist.github.com/802b397561971c1124854b300be76925
Prepared the gist for dance.3.gif in https://gist.github.com/30fe6284f579b53e43c5567220f84dd4
Prepared the gist for dance.2.gif in https://gist.github.com/611b590841b1a6bb10fae4fe0a3f2bd1
Prepared the gist for dance.4.gif in https://gist.github.com/fc0f01a623b4f78ae4916e7379101242
Username for 'https://gist.github.com': Username for 'https://gist.github.com': Username for 'https://gist.github.com': Username for 'https://gist.github.com': Username for 'https://gist.github.com': Username for 'https://gist.github.com': 
```

Any tip?

**Comment by cococ0j** [comment]
'cause you never use gist on your local machine. Try clone, edit, commit then push one of your own gists on your local machine. You will be asked for username and password. After that, when you use Mathdroid's script, it will not ask your username and password again.

**Comment by lubien** [comment]
Interesting. Shouldn't gist use my GitHub ssh token?

**Comment by cococ0j** [comment]
> Interesting. Shouldn't gist use my GitHub ssh token?

Not sure. I was asked for username and passwd. Solved in this way.

**Comment by lubien** [comment]
@cococ0j thanks for your help. I'm still getting `fatal: Authentication failed for` when I try to manually push gist over HTTPs (probably because I use 2fa and it never asked for it)

To be honest I already got around over the issue manually saving the images beforehand so this issue will be helpful for people in the future.

Perhaps @mathdroid could add this as a Known Issues section on README.

Have a nice day, thank you ;)

**Comment by cococ0j** [comment]
@lubien No worries, mate. Hope you can find a solution.
